"""Create a contact-enriched copy of a captured candidate resume.

The source resume pages are kept unchanged. A Medhunt contact page is
prepended using the contact data already committed to the candidate record.
"""
from __future__ import annotations

from io import BytesIO
from pathlib import Path

from . import phone_policy


class ContactSheetRefreshError(RuntimeError):
    """A prior Medhunt contact page could not be removed safely."""


def _clean_values(values, limit: int = 5) -> list[str]:
    output: list[str] = []
    seen: set[str] = set()
    for value in values or []:
        cleaned = str(value or "").strip()
        key = cleaned.casefold()
        if not cleaned or key in seen:
            continue
        seen.add(key)
        output.append(cleaned)
        if len(output) >= limit:
            break
    return output


def enriched_filename(filename: str) -> str:
    source = Path(filename or "resume.pdf")
    stem = source.stem.strip() or "resume"
    if stem.casefold().endswith(" - enriched"):
        return f"{stem}.pdf"
    return f"{stem} - enriched.pdf"


def add_contact_sheet(data: bytes, candidate: dict) -> tuple[bytes, bool]:
    """Return ``(pdf_bytes, embedded)`` for a captured PDF.

    Invalid/non-standard test fixtures are returned unchanged. Real Indeed
    PDFs are parsed and receive a new first page containing matched contact
    details. This preserves the source pages exactly as received.
    """
    latest_phone = phone_policy.latest_phone_detail(candidate)
    phones = _clean_values(
        [latest_phone.get("value")] if latest_phone else [],
        limit=1,
    )
    emails = _clean_values(candidate.get("emails"))
    phone_kind = str(latest_phone.get("kind") or "") if latest_phone else ""
    if not phones and not emails:
        return data, False
    try:
        from pypdf import PdfReader, PdfWriter
        from reportlab.lib.colors import HexColor
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas

        source_reader = PdfReader(BytesIO(data), strict=False)
        if not source_reader.pages:
            return data, False

        contact_buffer = BytesIO()
        # Keep retry output deterministic so an identical capture can be
        # recognized by checksum instead of creating another stored version.
        page = canvas.Canvas(contact_buffer, pagesize=letter, invariant=1)
        width, height = letter
        accent = HexColor("#0E9384")
        dark = HexColor("#102A43")
        muted = HexColor("#617580")

        page.setFillColor(accent)
        page.rect(0, height - 112, width, 112, stroke=0, fill=1)
        page.setFillColorRGB(1, 1, 1)
        page.setFont("Helvetica-Bold", 23)
        page.drawString(42, height - 64, "Medhunt Candidate Contact")
        page.setFont("Helvetica", 10)
        page.drawString(42, height - 86, "Matched contact data attached to the original Indeed resume")

        y = height - 158
        page.setFillColor(dark)
        page.setFont("Helvetica-Bold", 19)
        page.drawString(42, y, str(candidate.get("name") or "Candidate")[:100])
        y -= 24
        location = str(candidate.get("location") or "").strip()
        if location:
            page.setFillColor(muted)
            page.setFont("Helvetica", 11)
            page.drawString(42, y, location[:120])
            y -= 38
        else:
            y -= 18

        def section(label: str, values: list[str]) -> None:
            nonlocal y
            page.setFillColor(accent)
            page.setFont("Helvetica-Bold", 11)
            page.drawString(42, y, label.upper())
            y -= 21
            page.setFillColor(dark)
            page.setFont("Helvetica", 12)
            if values:
                for value in values:
                    page.drawString(56, y, value[:120])
                    y -= 20
            else:
                page.setFillColor(muted)
                page.drawString(56, y, "Not available")
                y -= 20
            y -= 20

        section("Email", emails)
        section(
            "Other phone" if phone_kind == "other"
            else ("Mobile" if phone_kind == "mobile" else "Phone"),
            phones,
        )

        confidence = float(candidate.get("confidence") or 0)
        page.setFillColor(muted)
        page.setFont("Helvetica", 9)
        if confidence > 0:
            page.drawString(42, 91, f"Identity-match confidence: {round(confidence * 100)}%")
        page.drawString(
            42,
            68,
            "The original resume follows unchanged. Contact ownership/deliverability may require separate verification.",
        )
        page.drawString(42, 51, "Generated by Medhunt Sourcing Assistant")
        page.save()
        contact_buffer.seek(0)

        writer = PdfWriter()
        writer.add_page(PdfReader(contact_buffer).pages[0])
        for source_page in source_reader.pages:
            writer.add_page(source_page)
        writer.add_metadata({
            "/Title": f"{candidate.get('name') or 'Candidate'} - Enriched Resume",
            "/Author": "Medhunt Sourcing Assistant",
            "/RadixsolCandidateId": str(candidate.get("id") or ""),
            "/RadixsolEmails": "; ".join(emails),
            "/RadixsolPhones": "; ".join(phones),
        })
        output = BytesIO()
        writer.write(output)
        enriched = output.getvalue()
        return (enriched, True) if enriched.startswith(b"%PDF-") else (data, False)
    except Exception:
        # Resume capture must remain available for unusual PDFs. The caller
        # reports whether a contact sheet was embedded so it is never implied
        # that an untouched fallback contains contact data.
        return data, False


def refresh_contact_sheet(data: bytes, candidate: dict) -> tuple[bytes, bool]:
    """Render the contact page from the candidate's current safe projection.

    Captured resumes are immutable storage snapshots, but a recruiter may
    download one after a newer trusted phone was saved (or after an old contact
    expired). A Medhunt-marked first page is therefore removed before the
    current contact page is rendered. Unmarked source PDFs simply receive a
    page in the normal way. If no current contact is allowed, the old Medhunt
    page is removed instead of exposing stale data.
    """
    marked = (
        b"/RadixsolCandidateId" in data
        or b"Medhunt Sourcing Assistant" in data
    )
    try:
        from pypdf import PdfReader, PdfWriter

        reader = PdfReader(BytesIO(data), strict=False)
        metadata = reader.metadata or {}
        marked = marked or bool(
            metadata.get("/RadixsolCandidateId") is not None
            or str(metadata.get("/Author") or "").strip()
            == "Medhunt Sourcing Assistant"
        )
        if not marked:
            return add_contact_sheet(data, candidate)
        if len(reader.pages) <= 1:
            raise ContactSheetRefreshError(
                "The marked PDF does not contain an original resume page."
            )

        source = BytesIO()
        writer = PdfWriter()
        for page in reader.pages[1:]:
            writer.add_page(page)
        writer.write(source)
        refreshed, embedded = add_contact_sheet(source.getvalue(), candidate)
        return refreshed, embedded
    except ContactSheetRefreshError:
        raise
    except Exception:
        if marked:
            # Returning the stored artifact here could expose a contact that
            # has since expired or entered the DNC list. Fail closed instead.
            raise ContactSheetRefreshError(
                "The existing Medhunt contact page could not be refreshed safely."
            )
        # An unmarked source PDF contains no Medhunt contact page to leak.
        return data, False
